-- member table
CREATE TABLE MEMBER(
  NUM int PRIMARY KEY auto_increment,
  ID VARCHAR(20) NOT NULL,
  PASS VARCHAR(20) NOT NULL,
  NAME VARCHAR(30) NOT NULL,
  AGE int not null,
  EMAIL VARCHAR(30) NOT NULL,
  PHONE VARCHAR(30) NOT NULL
);


-- 조회
SELECT * FROM MEMBER;

-- 추가
INSERT INTO MEMBER(ID, PASS, NAME, AGE, EMAIL, PHONE)
VALUES('admin', 'admin', '관리자', 40, 'abc@abc.xyz','010-1111-2313');

-- 수정
UPDATE MEMBER SET AGE=35, PHONE='010-3222-1333' WHERE ID='admin';

--삭제
DELETE FROM MEMBER WHERE ID='admin'